### ISSUE TITLE
No support for Krowi's Extended Vendor UI

### ISSUE THREAD

**Issue by Ookami313** [kaelonR/WoW-BuyemAll-live#10]
Updated to 4.0.0, Upon logging into the game I get the following error. Thanks.

120x ...faceBuyEmAll/MerchantFrame/BuyEmAllFrame.lua:364: attempt to index local 'itemButton' (a nil value)
[string "@BuyEmAll/MerchantFrame/BuyEmAllFrame.lua"]:364: in function `BuyEmAllFrame_UpdateMerchantInfo'
[string "@BuyEmAll/MerchantFrame/BuyEmAllFrame.lua"]:187: in function `BuyEmAllFrame_Update'
[string "@BuyEmAll/MerchantFrame/BuyEmAllFrame.lua"]:87: in function <...faceBuyEmAll/MerchantFrame/BuyEmAllFrame.lua:79>

Locals:
numMerchantItems = 0
name = nil
texture = nil
price = nil
stackCount = nil
numAvailable = nil
isPurchasable = nil
isUsable = nil
extendedCost = nil
currencyID = nil
(for index) = 13
(for limit) = 30
(for step) = 1
i = 13
index = 13
itemButton = nil
merchantButton = nil
merchantMoney = nil
merchantAltCurrency = nil
(*temporary) = "BuyEmAllItem13AltCurrencyFrame"
(*temporary) = "13"
(*temporary) = "AltCurrencyFrame"
(*temporary) = "AltCurrencyFrame"
(*temporary) = 0.400000
(*temporary) = BuyEmAllItem12SlotTexture {
}
(*temporary) = 0.400000
(*temporary) = 0.400000
(*temporary) = 0.400000
(*temporary) = "attempt to index local 'itemButton' (a nil value)"
MAX_MONEY_DISPLAY_WIDTH = 120

**Comment by fraerie** [comment]
I'm not usure if it's related to the above error - I've been getting spammed with the following error:

WARNING> code issue - function for [HookOpenAllBags:BuyEmAllFrame] was not found - please notify the author so it can be fixed.

**Comment by Odysseas68** [comment]
Same error in login with v4.0.0:

253x ...faceBuyEmAll/MerchantFrame/BuyEmAllFrame.lua:364: attempt to index local 'itemButton' (a nil value)
[string "@BuyEmAll/MerchantFrame/BuyEmAllFrame.lua"]:364: in function `BuyEmAllFrame_UpdateMerchantInfo'
[string "@BuyEmAll/MerchantFrame/BuyEmAllFrame.lua"]:187: in function `BuyEmAllFrame_Update'
[string "@BuyEmAll/MerchantFrame/BuyEmAllFrame.lua"]:87: in function <...faceBuyEmAll/MerchantFrame/BuyEmAllFrame.lua:79>

Locals:
numMerchantItems = 0
name = nil
texture = nil
price = nil
stackCount = nil
numAvailable = nil
isPurchasable = nil
isUsable = nil
extendedCost = nil
currencyID = nil
(for index) = 13
(for limit) = 20
(for step) = 1
i = 13
index = 13
itemButton = nil
merchantButton = nil
merchantMoney = nil
merchantAltCurrency = nil
(*temporary) = "BuyEmAllItem13AltCurrencyFrame"
(*temporary) = "13"
(*temporary) = "AltCurrencyFrame"
(*temporary) = "AltCurrencyFrame"
(*temporary) = 0.400000
(*temporary) = BuyEmAllItem12SlotTexture {
}
(*temporary) = 0.400000
(*temporary) = 0.400000
(*temporary) = 0.400000
(*temporary) = "attempt to index local 'itemButton' (a nil value)"
MAX_MONEY_DISPLAY_WIDTH = 120

**Comment by kaelonR** [comment]
Thanks. Will look into this ASAP.

**Comment by kaelonR** [comment]
@Ookami313 @Odysseas68 This error seems to indicate that another addon has overriden the `MERCHANT_ITEMS_PER_PAGE` variable, which is normally 10. This in turn seems to indicate that there's an addon active which tries to trick the merchant frame into showing more items at the same time.

Can I get a list of addons you're using? especially anything related to merchants or bag inventory is interesting.

**Comment by Sookhaal** [comment]
Hi!
I'm having the same problem, here are two addons that modifies the `MERCHANT_ITEMS_PER_PAGE` variable and cause an error:
https://www.curseforge.com/wow/addons/krowi-extended-vendor-ui (this is the one I use personally)
https://www.curseforge.com/wow/addons/elvui-windtools (the extend merchant pages setting in particular)

**Comment by kaelonR** [comment]
> Hi! I'm having the same problem, here are two addons that modifies the `MERCHANT_ITEMS_PER_PAGE` variable and cause an error: https://www.curseforge.com/wow/addons/krowi-extended-vendor-ui (this is the one I use personally) https://www.curseforge.com/wow/addons/elvui-windtools (the extend merchant pages setting in particular)

Thank you. 

I just fixed the error in v4.0.1, but the 'fix' here was to hardcode `MERCHANT_ITEMS_PER_PAGE` to 10 within the BuyEmAll context, so that the code won't attempt to set data in more than 10 buttons.

This means BuyEmAll currently has no support for Krowi's Extended Vendor UI, as BuyEmAll replaces the vendor UI.

I will look into adding support for Krowi's Extended Vendor UI in the near future.

**Comment by kaelonR** [comment]
After some investigation, it turns out changes are needed in the code of the _Krowi's Extended Vendor UI_ in order to make _BuyEmAll v4_ and _Krowi's Extended Vendor UI_ work together. I've actually gone ahead and made changes to the plugin's code, and opened a request to the author of _Krowi's Extended Vendor UI_ to include the changes in the official version.

You can follow that PR here:
https://github.com/TheKrowi/Krowi_ExtendedVendorUI/pull/40

Once Krowi's Extended Vendor UI is updated to include these changes, Krowi's and BuyEmAll v4.0.2+ will be able to work together.

**Comment by Odysseas68** [comment]
Also with this change if you set Krowi's Extended Vendor UI  to bigger frame (double) BuyEmAll left an invisible frame. My KEVU setup: Rows 5 / Columns 4. If you click out of the vendor frame (right side) you will see that your character can't move.

**Comment by kaelonR** [comment]
Should be fixed with v4.1.1 now.

**Comment by Sookhaal** [comment]
No more errors on my end, either using Krowi's Extended Vendor UI or windtool extend merchant pages feature.

Thanks for the fix 👍
