### ISSUE TITLE
v4.0.0 incompatible with several other addons

### ISSUE THREAD

**Issue by hollo6** [kaelonR/WoW-BuyemAll-live#11]
Hi,

Would it be possible to make the new version play nice with other addons?

It triggers the following error in ArkInventory:
[11:12:01] ArkInventory: WARNING> code issue - function for [HookOpenAllBags:BuyEmAllFrame] was not found - please notify the author so it can be fixed

And also it makes SellJunk unusable (its button doesn't show up at all).

The old version still works fine but would be nice to not be stuck with that forever. :)

Thanks!

**Comment by kaelonR** [comment]
This has been fixed in v4.0.1. The ArkInventory warning will no longer show up, and I've added compatibility for SellJunk by moving its button to BuyEmAll's frame when SellJunk is loaded on your game client. :)

**Comment by hollo6** [comment]
You're awesome, thank you!
