### ISSUE TITLE
Error spam since last update. 

### ISSUE THREAD

**Issue by TehGOOSE** [kaelonR/WoW-BuyemAll-live#12]
I use elv UI if that helps at all - running latest version

22x ...faceBuyEmAll/MerchantFrame/BuyEmAllFrame.lua:364: attempt to index local 'itemButton' (a nil value)
[string "@BuyEmAll/MerchantFrame/BuyEmAllFrame.lua"]:364: in function `BuyEmAllFrame_UpdateMerchantInfo'
[string "@BuyEmAll/MerchantFrame/BuyEmAllFrame.lua"]:187: in function `BuyEmAllFrame_Update'
[string "@BuyEmAll/MerchantFrame/BuyEmAllFrame.lua"]:87: in function <...faceBuyEmAll/MerchantFrame/BuyEmAllFrame.lua:79>

Locals:
numMerchantItems = 0
name = nil
texture = nil
price = nil
stackCount = nil
numAvailable = nil
isPurchasable = nil
isUsable = nil
extendedCost = nil
currencyID = nil
(for index) = 13
(for limit) = 20
(for step) = 1
i = 13
index = 13
itemButton = nil
merchantButton = nil
merchantMoney = nil
merchantAltCurrency = nil
(*temporary) = "BuyEmAllItem13AltCurrencyFrame"
(*temporary) = "13"
(*temporary) = "AltCurrencyFrame"
(*temporary) = "AltCurrencyFrame"
(*temporary) = 0.400000
(*temporary) = BuyEmAllItem12SlotTexture {
 PixelSnapDisabled = true
}
(*temporary) = BuyEmAllItem12SlotTexture {
 PixelSnapDisabled = true
}
(*temporary) = "attempt to index local 'itemButton' (a nil value)"
MAX_MONEY_DISPLAY_WIDTH = 120

**Comment by kaelonR** [comment]
This error has been fixed now.
