### ISSUE TITLE
BuyEmAll breaks merchant integration for Scrap

### ISSUE THREAD

**Issue by KyrosKrane** [kaelonR/WoW-BuyemAll-live#14]
### Description:
Scrap is an addon for selling junk; it also allows you to set specific items as junk by dropping them on the button Scrap puts in the merchant UI, replacing the default sell junk button. With BuyEmAll's replacement of the merchant UI, Scrap's button no longer appears in the when using a merchant. This breaks the ability to set and unset items as junk in Scrap by dropping them on its button.

No lua errors are generated.

Tested with the following addons:
BuyEmAll retail v4.0.2
Scrap (Junk Seller) v11.0.10
Buggrabber/Bugsack (latest)
Other addons disabled.

### Steps to reproduce:

1. Disable BuyEmAll and log in.
2. Go to a vendor and open the pane
3. Note that the default UI sell junk button has been replaced by Scrap's button.
4. Log out, enable BuyEmAll, and log back in.
5. Open the vendor pane
6. Note that the Scrap button does not appear.

**Comment by kaelonR** [comment]
Can Reproduce, should be an easy fix. Will include compatibility with Scrap in v4.0.3.

**Comment by kaelonR** [comment]
Just released 4.0.3, which has restored compatibility with Scrap. The Sell Junk button is replaced by Scrap's Sell Scrap button again, and the Scrap tab is also available.
