### ISSUE TITLE
LUA Error when opening a vendor window v4.0.5

### ISSUE THREAD

**Issue by fraerie** [kaelonR/WoW-BuyemAll-live#15]
1x BuyEmAll/MerchantFrame/glue.lua:115: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@BuyEmAll/MerchantFrame/glue.lua"]:115: in function <BuyEmAll/MerchantFrame/glue.lua:113>
[string "=[C]"]: in function `BuyEmAllFrame_MerchantShow'
[string "@BuyEmAll/MerchantFrame/glue.lua"]:3: in function <BuyEmAll/MerchantFrame/glue.lua:2>
[string "=[C]"]: in function `showFunc'
[string "@Blizzard_UIPanels_Game/Shared/PlayerInteractionFrameManager.lua"]:202: in function <...Panels_Game/Shared/PlayerInteractionFrameManager.lua:187>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Blizzard_UIPanels_Game/Shared/PlayerInteractionFrameManager.lua"]:240: in function <...Panels_Game/Shared/PlayerInteractionFrameManager.lua:237>

Locals:
(*temporary) = nil
(*temporary) = "table expected, got nil"

**Comment by fraerie** [comment]
also getting


5x [ADDON_ACTION_BLOCKED] AddOn 'BuyEmAll' tried to call the protected function 'MultiBarLeftButton12:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:488: in function `UpdatePressAndHoldAction'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:554: in function `Update'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:506: in function `UpdateAction'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:991: in function `OnEvent'
[string "@Blizzard_ActionBar/Mainline/ActionButton.lua"]:207: in function <Blizzard_ActionBar/Mainline/ActionButton.lua:204>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**Comment by kaelonR** [comment]
Should be resolved with v4.1.1.
