### ISSUE TITLE
Various issues with new versions

### ISSUE THREAD

**Issue by hollo6** [kaelonR/WoW-BuyemAll-live#16]
v3.5.17: works fine
v4.0.2: vendor frame cannot be paged when a profession window is open
v4.1.0: addon won't load, throws the following LUA errors on login/reload:

2x BuyEmAll/localisation/enUS.lua:15: attempt to index global 'BuyEmAll' (a nil value)
[string "@BuyEmAll/localisation/enUS.lua"]:15: in main chunk

Locals:
(*temporary) = nil
(*temporary) = <table> {
 STACK = "Stack"
 STACK_SIZE = "Stack size"
 CONFIRM = "Are you sure you want to buy
 %d × %s?"
 STACK_PURCH = "Stack purchase"
 AFFORD = "You can afford"
 PARTIAL = "Partial stack"
 MAX_PURCH = "Maximum purchase"
 AVAILABLE = "Vendor has"
 MAX = "Max"
 FIT = "You can fit"
}
(*temporary) = "attempt to index global 'BuyEmAll' (a nil value)"

2x BuyEmAll/BuyEmAll.lua:9: attempt to index local 'L' (a nil value)
[string "@BuyEmAll/BuyEmAll.lua"]:9: in main chunk

Locals:
L = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'L' (a nil value)"

2x [string "*BuyEmAll.xml:256_OnLoad"]:1: attempt to call method 'OnLoad' (a nil value)
[string "*BuyEmAll.xml:256_OnLoad"]:1: in function <[string "*BuyEmAll.xml:256_OnLoad"]:1>

Locals:
self = BuyEmAllFrame {
}
(*temporary) = nil
(*temporary) = <table> {
}
(*temporary) = "attempt to call method 'OnLoad' (a nil value)"

**Comment by kaelonR** [comment]
4.1.1 should work now.

**Comment by hollo6** [comment]
Looks fine now, thank you!
